In [14]:
p=[]
q=[]
for i in range(5):
    a=int((input("enter item for list 1 :")))
    p.append(a)
for i in range(5):
    b=int((input("enter item for list 2 :")))
    q.append(b)

arr1= np.array(p)
arr2= np.array(q)

print(arr1)
print(arr2)

c=np.concatenate([arr1,arr2])
print(c)

print(np.sort(arr1))
print(np.sort(arr2))
print(np.sort(c))

enter item for list 1 :10
enter item for list 1 :20
enter item for list 1 :30
enter item for list 1 :40
enter item for list 1 :50
enter item for list 2 :5
enter item for list 2 :10
enter item for list 2 :15
enter item for list 2 :20
enter item for list 2 :25
[10 20 30 40 50]
[ 5 10 15 20 25]
[10 20 30 40 50  5 10 15 20 25]
[10 20 30 40 50]
[ 5 10 15 20 25]
[ 5 10 10 15 20 20 25 30 40 50]
