In [5]:
import numpy as np

In [6]:
arr= np.arange(9).reshape(3,3)
arr1= np.array([[13,14,17],[18,52,16],[22,89,90]])
print(arr)
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[13 14 17]
 [18 52 16]
 [22 89 90]]


In [7]:
v= np.vstack((arr, arr1))
h= np.hstack((arr, arr1))

print(v)
print(" ")
print(h)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [13 14 17]
 [18 52 16]
 [22 89 90]]
 
[[ 0  1  2 13 14 17]
 [ 3  4  5 18 52 16]
 [ 6  7  8 22 89 90]]
